name: CI

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name  }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

    - name: Checkout SDK
      uses: actions/checkout@v3
      with:
        repository: ps5-payload-dev/sdk
        path: sdk

    - name: Setup SDK
      working-directory: sdk
      run: |
        sudo apt update
        sudo apt install clang-18 lld-18
        make DESTDIR=${{ runner.tool_cache }}/ps5-payload-sdk clean install
        echo PS5_PAYLOAD_SDK=${{ runner.tool_cache }}/ps5-payload-sdk >> $GITHUB_ENV

    - name: Checkout Payload
      uses: actions/checkout@v3

    - name: Build Payload
      run: |
        make -f Makefile.ps5 clean all
        zip -r Payload.zip ftpsrv-ps5.elf

    - name: Upload Payload
      uses: actions/upload-artifact@v4
      with:
        name: Payload
        path: Payload.zip
        if-no-files-found: error

  release:
    needs: build
    permissions:
      contents: write

    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Payload
          path: .

      - name: Create GitHub Release (pre-release)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: true
          files: Payload.zip
